In [53]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv');

In [54]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [56]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [57]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [58]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [59]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [61]:
df['Review Rating'].head(30)

0     3.1
1     3.1
2     3.1
3     3.5
4     2.7
5     2.9
6     3.2
7     3.2
8     2.6
9     4.8
10    4.1
11    4.9
12    4.5
13    4.7
14    4.7
15    2.8
16    4.1
17    4.7
18    4.6
19    3.3
20    2.8
21    4.1
22    3.2
23    4.4
24    2.9
25    3.6
26    3.6
27    5.0
28    4.4
29    4.1
Name: Review Rating, dtype: float64

In [62]:
df.columns = df.columns.str.replace('_', '', regex=False)

In [63]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [64]:
df.columns = df.columns.str.strip().str.lower()
df.columns = df.columns.str.replace(' ', '_', regex=False)
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [65]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases']

In [66]:
#create columns age_group
labels=['Young Adult','Adult','middle_aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels = labels)

In [67]:
df[['age','age_group']].head(10)

   age    age_group
0   55  middle_aged
1   19  Young Adult
2   50  middle_aged
3   21  Young Adult
4   45  middle_aged
5   46  middle_aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  middle_aged

In [68]:
# create colimn purchase_frequence_days
frequence_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Annually': 365
}

In [69]:
df['purchase_frequence_days'] = df['frequency_of_purchases'].map(frequence_mapping)

In [70]:
print(df['purchase_frequence_days'].isna().sum())

0

In [71]:
df['purchase_frequence_days'] = df['purchase_frequence_days'].astype(int)

In [72]:
df[['purchase_frequence_days', 'frequency_of_purchases']].head(10)

   purchase_frequence_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [73]:
print(df['frequency_of_purchases'].unique())

<ArrowStringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [74]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [75]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [76]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequence_days'],
      dtype='str')

In [77]:
import sys
print(sys.executable)

C:\ProgramData\anaconda3\python.exe

In [78]:
%pip install "psycopg[binary]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg[binary] in C:\Users\Lachi Meshram\AppData\Roaming\Python\Python314\site-packages (3.3.6)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from psycopg[binary]) (2026.2)
Requirement already satisfied: psycopg-binary==3.3.6 in C:\Users\Lachi Meshram\AppData\Roaming\Python\Python314\site-packages (from psycopg[binary]) (3.3.6)
Note: you may need to restart the kernel to use updated packages.

In [79]:
import psycopg
print(psycopg.__version__)

3.3.6

In [32]:
!pip install psycopg[binary] sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg[binary] in C:\Users\Lachi Meshram\AppData\Roaming\Python\Python314\site-packages (3.3.6)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from psycopg[binary]) (2026.2)
Requirement already satisfied: psycopg-binary==3.3.6 in C:\Users\Lachi Meshram\AppData\Roaming\Python\Python314\site-packages (from psycopg[binary]) (3.3.6)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)

In [33]:
from sqlalchemy import create_engine

In [80]:
import psycopg

conn = psycopg.connect(
    host="localhost",
    port=5432,
    dbname="postgres",
    user="postgres",
    password="root"
)

conn.autocommit = True

print("Connected to PostgreSQL!")

Connected to PostgreSQL!

In [35]:
cur = conn.cursor()

cur.execute("CREATE DATABASE customer_behavior")

print("Database created successfully!")

DuplicateDatabase: database "customer_behavior" already exists

In [36]:
cur.close()
conn.close()

In [81]:
from sqlalchemy import create_engine

username = "postgres"
password = "root"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}"
)

table_name = "customer"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [82]:
df.to_sql("customer", engine, if_exists="replace", index=False)

-1

In [83]:
pd.read_sql("SELECT COUNT(*), COUNT(review_rating) FROM customer;", engine)

   count  count
0   3900   3900